name: CI

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, closed]
env:
  # .NET Configuration
  DOTNET_VERSION: '8.0.x'
  
  # Solution and Project Paths
  SOLUTION_PATH: 'server/IssueTracker'
  
  # Build Configuration
  BUILD_CONFIGURATION: 'Release'
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: 📦 Cache NuGet Packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-  
                
      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}
        
      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
        
      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --configuration  ${{ env.BUILD_CONFIGURATION }} --verbosity normal
