name: CI

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, closed]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore server/IssueTracker/IssueTracker.sln
      - name: Build
        run: dotnet build server/IssueTracker/IssueTracker.sln --no-restore --configuration Release
      - name: Test
        run: dotnet test server/IssueTracker/IssueTracker.sln --no-build --configuration Release --verbosity normal
